v0.8.x [firebase-walletconnect-push]
WalletConnect/firebase-walletconnect-push pull request #2
Opened 2018-12-04 16:13 UTC by pedrouid

2018-12-04 16:27 UTC, ligi commented on functions/index.js
> +  const body = 'New Request'
the body is not needed - see #1

2018-12-04 16:27 UTC, ligi requested changes
the body is not needed - see #1

2019-01-23 19:14 UTC, pedrouid commented
Closed. Changes introduced in v1.0.0-beta instead

https://github.com/WalletConnect-Labs/walletconnect-push

2019-01-23 19:14 UTC, closed without merging

2019-01-23 20:17 UTC, ligi commented
very strange - is there any document where I can read why 1.0.0 makes this obsolete?

2019-01-23 20:27 UTC, ligi commented
Ah wait - mixed up the PRs - thought this is about the notification type.

2019-01-23 22:00 UTC, pedrouid commented
All v0.8.x changes have been pushed to the v1.0.0-beta. 
All the new repos are temporarily listed here:
https://github.com/WalletConnect-Labs